project_id = "vrcyjmfpteoccqdmdmqn"

[functions.extract-license-expiry]
verify_jwt = true

[functions.extract-tarjeta-circulacion]
verify_jwt = true

[functions.gmail-auth]
verify_jwt = true

[functions.gmail-callback]
verify_jwt = false

[functions.gmail-api]
verify_jwt = true

[functions.google-places-autocomplete]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.confirmar-oc]
verify_jwt = false

[functions.auto-reschedule-deliveries]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.parse-order-email]
verify_jwt = true

[functions.parse-csf]
verify_jwt = true

[functions.create-client-user]
verify_jwt = true

[functions.parse-excel-order]
verify_jwt = true

[functions.send-order-authorized-email]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true
