import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { corsHeaders } from "../_shared/cors.ts";

interface CuadrillaInput {
  empleado_id: string;
  rol: "chofer" | "ayudante";
  orden_ayudante?: number;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { entrega_id, cuadrilla } = await req.json() as {
      entrega_id: string;
      cuadrilla: CuadrillaInput[];
    };

    if (!entrega_id) return respond(400, { error: "entrega_id requerido" });

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    // 1. Load entrega with full joins
    const { data: entrega, error: eErr } = await supabase
      .from("entregas")
      .select(`
        id, orden_entrega, notas,
        pedidos:pedido_id(
          id, folio, fecha_pedido,
          clientes:cliente_id(id, nombre, razon_social, rfc, direccion, telefono),
          pedidos_detalles(
            id, cantidad, precio_unitario,
            productos:producto_id(id, nombre, codigo, unidad, peso_kg, unidad_sat)
          )
        ),
        rutas:ruta_id(id, folio, fecha_ruta, vehiculo_id,
          vehiculos:vehiculo_id(id, nombre, placa, tipo)
        )
      `)
      .eq("id", entrega_id)
      .single();

    if (eErr || !entrega) return respond(404, { error: "Entrega no encontrada" });

    const pedido = entrega.pedidos as any;
    const cliente = pedido?.clientes;
    const detalles = pedido?.pedidos_detalles || [];
    const ruta = entrega.rutas as any;
    const vehiculo = ruta?.vehiculos;

    // 2. Check Carta Porte link
    let cartaPorteId: string | null = null;
    if (ruta?.id) {
      const { data: cp } = await supabase
        .from("cartas_porte")
        .select("id")
        .eq("ruta_id", ruta.id)
        .in("estado", ["borrador", "validado", "timbrado"])
        .limit(1)
        .maybeSingle();
      cartaPorteId = cp?.id || null;
    }

    // 3. Calculate totals
    let totalPedidos = 0;
    let pesoBruto = 0;
    const lineas = detalles.map((d: any, idx: number) => {
      const prod = d.productos;
      const cant = parseFloat(d.cantidad) || 0;
      const peso = (prod?.peso_kg || 0) * cant;
      totalPedidos += cant;
      pesoBruto += peso;
      return {
        pedido_detalle_id: d.id,
        producto_id: prod?.id,
        orden_linea: idx + 1,
        codigo_producto: prod?.codigo || "",
        descripcion_producto: prod?.nombre || "",
        cantidad_pedida: cant,
        cantidad_surtida: cant, // assume fully stocked by almacen
        unidad: prod?.unidad || "pz",
        lote: null,
      };
    });

    // 4. Get user from auth
    const authHeader = req.headers.get("Authorization");
    let userId: string | null = null;
    if (authHeader) {
      const { data: { user } } = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
      userId = user?.id || null;
    }

    // 5. Insert hoja_salida (folio auto-generated by trigger)
    const { data: hoja, error: hErr } = await supabase
      .from("hojas_salida")
      .insert({
        folio: "", // trigger fills
        entrega_id,
        pedido_id: pedido?.id,
        carta_porte_id: cartaPorteId,
        requiere_carta_porte: !!cartaPorteId,
        estado: "generada",
        cliente_razon_social: cliente?.razon_social || cliente?.nombre || "",
        cliente_rfc: cliente?.rfc || "",
        cliente_direccion: cliente?.direccion || "",
        cliente_contacto_nombre: cliente?.nombre || "",
        cliente_contacto_telefono: cliente?.telefono || "",
        vehiculo_id: vehiculo?.id || null,
        vehiculo_placa: vehiculo?.placa || "",
        vehiculo_descripcion: vehiculo?.nombre || "",
        ruta_id: ruta?.id || null,
        ruta_folio: ruta?.folio || "",
        total_items_pedidos: detalles.length,
        total_items_surtidos: detalles.length,
        total_bultos: Math.ceil(totalPedidos),
        peso_bruto_kg: pesoBruto,
        generada_por: userId,
      })
      .select()
      .single();

    if (hErr || !hoja) return respond(500, { error: `Error creando hoja: ${hErr?.message}` });

    // 6. Insert lines
    if (lineas.length > 0) {
      await supabase.from("hojas_salida_lineas").insert(
        lineas.map((l: any) => ({ ...l, hoja_salida_id: hoja.id }))
      );
    }

    // 7. Insert cuadrilla
    if (cuadrilla?.length) {
      // Fetch employee names
      const empIds = cuadrilla.map((c) => c.empleado_id);
      const { data: empleados } = await supabase
        .from("empleados")
        .select("id, nombre_completo")
        .in("id", empIds);
      const nameMap = new Map((empleados || []).map((e: any) => [e.id, e.nombre_completo]));

      await supabase.from("cuadrilla_hoja_salida").insert(
        cuadrilla.map((c) => ({
          hoja_salida_id: hoja.id,
          empleado_id: c.empleado_id,
          rol_en_entrega: c.rol,
          orden_ayudante: c.orden_ayudante || null,
          nombre_snapshot: nameMap.get(c.empleado_id) || "",
        }))
      );
    }

    // 8. Register conciliation event
    await supabase.from("eventos_conciliacion").insert({
      hoja_salida_id: hoja.id,
      entrega_id,
      momento_id: "sistema_genera_hoja",
      estado: "completado",
      usuario_id: userId,
      notas: `Hoja de Salida ${hoja.folio} generada automáticamente`,
    });

    // 9. Generate HTML
    const html = buildHojaSalidaHTML(hoja, lineas, cuadrilla || [], cliente, vehiculo, ruta, cartaPorteId);

    // 10. Upload to storage
    const encoder = new TextEncoder();
    const path = `pdfs/${hoja.folio}.html`;
    await supabase.storage.from("hojas-salida").upload(path, encoder.encode(html), {
      contentType: "text/html",
      upsert: true,
    });
    const { data: urlData } = supabase.storage.from("hojas-salida").getPublicUrl(path);

    // 11. Update with PDF URL
    await supabase.from("hojas_salida").update({ pdf_url: urlData.publicUrl }).eq("id", hoja.id);

    return respond(200, {
      exitoso: true,
      hoja_salida_id: hoja.id,
      folio: hoja.folio,
      pdf_url: urlData.publicUrl,
      html,
    });
  } catch (error) {
    return respond(500, { error: error.message });
  }
});

function respond(status: number, body: any) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function buildHojaSalidaHTML(
  hoja: any, lineas: any[], cuadrilla: any[], cliente: any, vehiculo: any, ruta: any, cartaPorteId: string | null
): string {
  const ITEMS_PER_PAGE = 10;
  const totalPages = Math.max(1, Math.ceil(lineas.length / ITEMS_PER_PAGE));
  const pesoTotal = lineas.reduce((s: number, l: any) => s + ((l.cantidad_surtida || 0) * 1), 0);

  const chofer = cuadrilla.find((c: any) => c.rol === "chofer");
  const ayudantes = cuadrilla.filter((c: any) => c.rol === "ayudante");

  let pages = "";
  for (let p = 0; p < totalPages; p++) {
    const pageLineas = lineas.slice(p * ITEMS_PER_PAGE, (p + 1) * ITEMS_PER_PAGE);
    const isFirst = p === 0;
    const isLast = p === totalPages - 1;

    pages += `
    <div class="page ${!isLast ? 'page-break' : ''}">
      ${isFirst ? `
      <div class="header">
        <div class="header-left">
          <div class="logo">ALMASA</div>
          <div class="subtitle">Abarrotes La Manita SA de CV</div>
          <div class="subtitle">Hermosillo, Sonora</div>
        </div>
        <div class="header-right">
          <div class="doc-title">HOJA DE SALIDA</div>
          <div class="folio">${hoja.folio}</div>
          <div class="fecha">${new Date(hoja.fecha_emision).toLocaleDateString("es-MX")}</div>
          ${cartaPorteId ? '<div class="cp-badge">Vinculada a Carta Porte</div>' : ''}
        </div>
      </div>

      <div class="info-grid">
        <div class="info-section">
          <div class="section-title">DESTINATARIO</div>
          <div class="info-row"><span class="lbl">Razón Social:</span> ${hoja.cliente_razon_social}</div>
          <div class="info-row"><span class="lbl">RFC:</span> ${hoja.cliente_rfc || '—'}</div>
          <div class="info-row"><span class="lbl">Dirección:</span> ${hoja.cliente_direccion || '—'}</div>
          <div class="info-row"><span class="lbl">Contacto:</span> ${hoja.cliente_contacto_nombre || '—'} ${hoja.cliente_contacto_telefono || ''}</div>
        </div>
        <div class="info-section">
          <div class="section-title">TRANSPORTE</div>
          <div class="info-row"><span class="lbl">Ruta:</span> ${hoja.ruta_folio || '—'}</div>
          <div class="info-row"><span class="lbl">Vehículo:</span> ${hoja.vehiculo_descripcion || '—'} ${hoja.vehiculo_placa ? `(${hoja.vehiculo_placa})` : ''}</div>
          <div class="info-row"><span class="lbl">Pedido:</span> ${hoja.pedido_id ? 'Vinculado' : '—'}</div>
          <div class="info-row"><span class="lbl">Entrega:</span> ${hoja.tipo_entrega === 'unica' ? 'Única' : hoja.tipo_entrega}</div>
        </div>
      </div>
      ` : `
      <div class="header-compact">
        <div><span class="logo-sm">ALMASA</span> — HOJA DE SALIDA</div>
        <div class="folio">${hoja.folio}</div>
      </div>
      `}

      <table class="products">
        <thead>
          <tr>
            <th style="width:30px">#</th>
            <th style="width:70px">Código</th>
            <th>Descripción</th>
            <th style="width:55px;text-align:center">Pedido</th>
            <th style="width:55px;text-align:center">Surtido</th>
            <th style="width:50px;text-align:center">Unidad</th>
            <th style="width:60px;text-align:center">Recibido</th>
          </tr>
        </thead>
        <tbody>
          ${pageLineas.map((l: any) => `
          <tr>
            <td>${l.orden_linea}</td>
            <td class="mono">${l.codigo_producto}</td>
            <td>${l.descripcion_producto}</td>
            <td style="text-align:center">${l.cantidad_pedida}</td>
            <td style="text-align:center">${l.cantidad_surtida}</td>
            <td style="text-align:center">${l.unidad}</td>
            <td></td>
          </tr>`).join("")}
        </tbody>
      </table>

      ${!isLast ? `<div class="page-footer">Continúa en página ${p + 2} de ${totalPages}</div>` : ""}

      ${isLast ? `
      <div class="totals-bar">
        <span>Total líneas: ${lineas.length}</span>
        <span>Bultos: ${hoja.total_bultos}</span>
        <span>Peso bruto: ${hoja.peso_bruto_kg?.toFixed(1) || 0} kg</span>
      </div>

      <div class="obs-section">
        <div class="obs-title">OBSERVACIONES DEL CLIENTE</div>
        <div class="obs-line"></div>
        <div class="obs-line"></div>
        <div class="obs-line"></div>
      </div>

      <div class="stamp-area">
        <div class="stamp-title">SELLO DEL CLIENTE</div>
        <div class="stamp-hint">Colocar sello aquí</div>
      </div>

      <div class="signatures">
        <div class="sig-box">
          <div class="sig-label">RECIBIÓ (Cliente)</div>
          <div class="sig-line"></div>
          <div class="sig-sub">Nombre, firma y fecha</div>
        </div>
        <div class="sig-box">
          <div class="sig-label">ENTREGÓ (Chofer)</div>
          <div class="sig-line"></div>
          <div class="sig-sub">${chofer ? `${chofer.nombre_snapshot || 'Chofer'}` : 'Nombre y firma'}</div>
        </div>
        ${ayudantes.map((a: any, i: number) => `
        <div class="sig-box">
          <div class="sig-label">AYUDANTE ${i + 1}</div>
          <div class="sig-line"></div>
          <div class="sig-sub">${a.nombre_snapshot || `Ayudante ${i + 1}`}</div>
        </div>`).join("")}
      </div>

      <div class="legal">
        Este documento NO sustituye el CFDI correspondiente. Conservar por 5 años conforme Art. 30 CFF.
        ${cartaPorteId ? 'Carta Porte 3.1 vinculada — consultar complemento fiscal por separado.' : ''}
      </div>

      <div class="footer">
        ALMASA — Abarrotes La Manita SA de CV · Hermosillo, Sonora · almasa.com.mx
        <br>Generado por ALMASA-OS · Página ${p + 1} de ${totalPages}
      </div>
      ` : ""}
    </div>`;
  }

  return `<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<title>Hoja de Salida ${hoja.folio}</title>
<style>
  @page{size:letter;margin:12mm}
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Inter',Arial,sans-serif;font-size:10px;color:#222;padding:12px}
  .page{position:relative}
  .page-break{page-break-after:always;margin-bottom:20px;padding-bottom:20px;border-bottom:1px dashed #ccc}
  .header{display:flex;justify-content:space-between;border-bottom:3px solid #c41e3a;padding-bottom:6px;margin-bottom:8px}
  .header-left .logo{font-family:'Cormorant Garamond',Georgia,serif;font-size:24px;font-weight:700;color:#c41e3a}
  .header-left .subtitle{font-size:8px;color:#666}
  .header-right{text-align:right}
  .header-right .doc-title{font-size:14px;font-weight:700;color:#c41e3a}
  .header-right .folio{font-family:'JetBrains Mono',monospace;font-size:13px;font-weight:600}
  .header-right .fecha{font-size:9px;color:#666}
  .cp-badge{display:inline-block;background:#e0f2fe;color:#0369a1;font-size:8px;padding:1px 6px;border-radius:3px;margin-top:2px}
  .header-compact{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #c41e3a;padding-bottom:4px;margin-bottom:6px}
  .logo-sm{font-family:'Cormorant Garamond',Georgia,serif;font-size:14px;font-weight:700;color:#c41e3a}
  .info-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px}
  .info-section{border:1px solid #e5e7eb;border-radius:4px;padding:6px}
  .section-title{font-size:8px;font-weight:700;color:#c41e3a;text-transform:uppercase;margin-bottom:3px;letter-spacing:0.5px}
  .info-row{font-size:9px;margin-bottom:1px}
  .info-row .lbl{color:#888;font-weight:600}
  table.products{width:100%;border-collapse:collapse;margin-bottom:8px}
  table.products th{background:#c41e3a;color:#fff;padding:4px 6px;font-size:8px;text-transform:uppercase;letter-spacing:0.3px}
  table.products td{padding:4px 6px;border:1px solid #e5e7eb;font-size:9px}
  table.products tr:nth-child(even){background:#fafafa}
  .mono{font-family:'JetBrains Mono',monospace;font-size:8px}
  .page-footer{text-align:center;font-size:8px;color:#999;margin-top:8px;font-style:italic}
  .totals-bar{display:flex;justify-content:space-around;background:#fef2f2;border:1px solid #fecaca;border-radius:4px;padding:6px;margin-bottom:8px;font-weight:600;font-size:10px}
  .obs-section{border:1px solid #e5e7eb;border-radius:4px;padding:8px;margin-bottom:8px}
  .obs-title{font-size:8px;font-weight:700;color:#c41e3a;margin-bottom:4px;text-transform:uppercase}
  .obs-line{border-bottom:1px dotted #ccc;height:18px}
  .stamp-area{border:2px dashed #c41e3a;border-radius:8px;text-align:center;padding:20px;margin-bottom:8px;min-height:80px}
  .stamp-title{font-size:10px;font-weight:700;color:#c41e3a}
  .stamp-hint{font-size:8px;color:#999;margin-top:4px}
  .signatures{display:flex;gap:8px;margin-bottom:8px;flex-wrap:wrap}
  .sig-box{flex:1;min-width:120px;border:1px solid #e5e7eb;border-radius:4px;padding:8px;text-align:center}
  .sig-label{font-size:7px;font-weight:700;color:#c41e3a;text-transform:uppercase;margin-bottom:25px}
  .sig-line{border-top:1px solid #333;margin-top:4px}
  .sig-sub{font-size:7px;color:#888;margin-top:2px}
  .legal{font-size:7px;color:#999;text-align:center;margin-bottom:6px;font-style:italic}
  .footer{text-align:center;font-size:7px;color:#aaa;border-top:1px solid #eee;padding-top:4px}
</style>
</head><body>${pages}</body></html>`;
}
