CREATE OR REPLACE FUNCTION update_empleado_completo(
  p_id uuid,
  p_nombre_completo text,
  p_nombre text DEFAULT NULL,
  p_primer_apellido text DEFAULT NULL,
  p_segundo_apellido text DEFAULT NULL,
  p_rfc text DEFAULT NULL,
  p_curp text DEFAULT NULL,
  p_fecha_nacimiento date DEFAULT NULL,
  p_telefono text DEFAULT NULL,
  p_email text DEFAULT NULL,
  p_fecha_ingreso date DEFAULT NULL,
  p_puesto text DEFAULT NULL,
  p_activo boolean DEFAULT true,
  p_notas text DEFAULT NULL,
  p_user_id uuid DEFAULT NULL,
  p_sueldo_bruto numeric DEFAULT NULL,
  p_periodo_pago text DEFAULT NULL,
  p_fecha_baja date DEFAULT NULL,
  p_motivo_baja text DEFAULT NULL,
  p_beneficiario text DEFAULT NULL,
  p_premio_asistencia_semanal numeric DEFAULT NULL,
  p_numero_seguro_social text DEFAULT NULL,
  p_contacto_emergencia_nombre text DEFAULT NULL,
  p_contacto_emergencia_telefono text DEFAULT NULL,
  p_tipo_sangre text DEFAULT NULL,
  p_estado_civil text DEFAULT NULL,
  p_numero_dependientes integer DEFAULT NULL,
  p_nivel_estudios text DEFAULT NULL,
  p_cuenta_bancaria text DEFAULT NULL,
  p_clabe_interbancaria text DEFAULT NULL
)
RETURNS void AS $$
BEGIN
  UPDATE empleados SET
    nombre_completo = p_nombre_completo,
    nombre = p_nombre,
    primer_apellido = p_primer_apellido,
    segundo_apellido = p_segundo_apellido,
    rfc = p_rfc,
    curp = p_curp,
    fecha_nacimiento = p_fecha_nacimiento,
    telefono = p_telefono,
    email = p_email,
    fecha_ingreso = p_fecha_ingreso,
    puesto = p_puesto,
    activo = p_activo,
    notas = p_notas,
    user_id = p_user_id,
    sueldo_bruto = p_sueldo_bruto,
    periodo_pago = p_periodo_pago,
    fecha_baja = p_fecha_baja,
    motivo_baja = p_motivo_baja,
    beneficiario = p_beneficiario,
    premio_asistencia_semanal = p_premio_asistencia_semanal,
    numero_seguro_social = p_numero_seguro_social,
    contacto_emergencia_nombre = p_contacto_emergencia_nombre,
    contacto_emergencia_telefono = p_contacto_emergencia_telefono,
    tipo_sangre = p_tipo_sangre,
    estado_civil = p_estado_civil,
    numero_dependientes = p_numero_dependientes,
    nivel_estudios = p_nivel_estudios,
    cuenta_bancaria = p_cuenta_bancaria,
    clabe_interbancaria = p_clabe_interbancaria
  WHERE id = p_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
