// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Interceptor global: detectar sesión perdida silenciosamente
supabase.auth.onAuthStateChange(async (event, session) => {
  if (!session && event !== 'SIGNED_OUT') {
    // Sin sesión activa y no fue logout manual → posible expiración
    const { error } = await supabase.auth.refreshSession();
    if (error) {
      // No se pudo renovar → forzar redirección a login
      window.location.href = '/auth';
    }
  }
});